service: SmileCentersMoons
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  enviroment:
    MONGO_DB_URL: ${env:MONGO_DB_URL, "none"}
    MONGO_DB_NAME: ${env:MONGO_DB_NAME, "none"}


functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

custom:
  dotenv:
    exclude: 
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
